services:
  db:
    image: postgres:16-alpine
    container_name: ar_shopping_world_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: arshop
      POSTGRES_PASSWORD: arshop
      POSTGRES_DB: ar_shopping_world
    ports:
      - "5432:5432"
    volumes:
      - ar_shopping_pgdata:/var/lib/postgresql/data

volumes:
  ar_shopping_pgdata:
